### ISSUE TITLE
Getting issue .finalize section after disk successfully uploaded

### ISSUE THREAD

**Issue by avisheksarkar20** [oVirt/ovirt-engine-sdk#41]
I have used upload-disk.py to upload qcow2 image to data center...however getting below errror

./upload-distk.py --engine-url 'https://xyz.net' --username='as665283@broadcom.net' --password-file=password  --sd-name='SEC-ABC' --cafile='/home/jenkins/crt/ca.crt' --disk-format="qcow2" --disk-sparse image-XYZ

Checking image...
Image format: qcow2
Disk format: cow
Disk content type: data
Disk provisioned size: 10737418240
Disk initial size: 5526847488
Disk name: image-avishek.qcow2
Connecting...
Creating disk...
Creating transfer session...
Uploading image...
[ 100.00% ] 10.00 GiB, 11.34 seconds, 903.09 MiB/s
Finalizing transfer session...
Traceback (most recent call last):
  File "./upload-dist1.py", line 300, in <module>
    transfer_service.finalize()
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/services.py", line 13971, in finalize
    return self._internal_action(action, 'finalize', None, headers, query, wait)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 299, in _internal_action
    return future.wait() if wait else future
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 296, in callback
    self._check_fault(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 132, in _check_fault
    self._raise_error(response, body)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
ovirtsdk4.AuthError: Fault reason is "Operation Failed". Fault detail is "[User is not authorized to perform this action.]". HTTP response code is 403.

**Comment by nirs** [comment]
This looks like ovirt engine bug, not an issue with the upload_disk.py example.

Please file an ovirt-engine bug here:
https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine

And attach engine log from your engine host (/var/log/ovirt-engine/engine.log)

**Comment by nirs** [comment]
@oliel I think we can close this issue.
